# Generated by Django 4.2.2 on 2023-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('qisqa_matn', models.CharField(max_length=200)),
                ('batafsil', models.TextField()),
                ('rasm', models.FileField(blank=True, null=True, upload_to='yangilik')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
